name: Tomochain CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.0-rc.1' # The Go version to download (if necessary) and use.
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.0-rc.1' # The Go version to download (if necessary) and use.
      - name: Build
        run: go run build/ci.go install
        env:
          GOPATH: /home/runner/go

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.0-rc.1' # The Go version to download (if necessary) and use.
      - name: Test
        run: go run build/ci.go test -coverage
        env:
          GOPATH: /home/runner/go